import 'package:flutter/material.dart';
import 'package:islami_application/layout%20screen/quran_Tap/soura_name.dart';

class QuranTap extends StatelessWidget {
  List<String> sura_name = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];

  @override
  Widget build(BuildContext context) {
    return  Column(
        children: [
          Expanded(
            flex: 1,
            child: Image(
              image: AssetImage(
                  "assets/images/layout screen/quran_tap/quran_header_logo.png"),
            ),
          ),
          Container(
            height: 1,
            width: double.infinity,
            color: Theme.of(context).accentColor,
          ),
          Container(
            margin: const EdgeInsets.symmetric(vertical: 10.0),
            child: Text("Sura Name",style: Theme.of(context).textTheme.headline5),
          ),
          Container(
            height: 1,
            width: double.infinity,
            color: Theme.of(context).accentColor,
          ),
          Expanded(
            flex: 3,
            child: ListView.separated(
              itemBuilder: (context, index) =>
                  SouraName(sour_name: sura_name[index],index: index),
              separatorBuilder: (context, index) => Container(
                width: double.infinity,
                color: Theme.of(context).accentColor,
                height: 1,
              ),
              itemCount: sura_name.length,
            ),
          )
        ],
      );
  }
}
